### ISSUE TITLE
Support SOAP 1.2 requests

### ISSUE THREAD

**Issue by filipedias** [gravity00/SimpleSOAPClient#13]
The handler "UsingRequestRawHandler" should support requests on SOAP 1.2 as the following example:

"
	.UsingRequestRawHandler((c, d) =>
	{
		d.Request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/soap+xml;charset=UTF-8;action=\"http://domain.com/Service/Request\"");
	})
"

Regards,
Filipe Dias

**Comment by gravity00** [comment]
Presently the client only supports SOAP standard 1.1. The version 2.0 will also support SOAP standard 1.2.
A work around would be passing an HTTP Client in the constructor that could construct the `Content-Type` values based on the existing `SOAPAction` header.

**Comment by gravity00** [comment]
Since the client now has to support different SOAP Envelope versions, the recommended way to create envelopes or headers is via the `SoapMessage` class. Example:

```csharp
var soapEnvelope11 = SoapMessage.V1Dot1.PrepareEnvelope();
var soapEnvelope12 = SoapMessage.V1Dot2.PrepareEnvelope();
```

Due to this requirements, model objects are now located in `SimpleSOAPClient.Models.V1Dot1.*` or `SimpleSOAPClient.Models.V1Dot2.*` namespaces and handlers now have methods for versions 1.1 and 1.2. Example:

```csharp
var handler = new DelegatingSoapHandler
{
	OnSoapEnvelopeV1Dot1RequestAction = args => 
	{
		
	},
	OnSoapEnvelopeV1Dot2RequestAction = args => 
	{
		
	},
	OnSoapEnvelopeV1Dot1ResponseAction = args => 
	{
		
	},
	OnSoapEnvelopeV1Dot2ResponseAction = args => 
	{
		
	}
};
```

Documentation and examples will be updated on release 1.0.0-RC04

**Comment by Lerke** [comment]
Hello @gravity00 
I'm trying to integrate a SOAP 1.2 service into my .NET Core 3.0 application. I found this issue which looks really promising, but I cannot find any of the V1Dot2 namespaces or functions. Were these removed from the project?

Thank you for your time. I'm using version 2.1.0 from Nuget.

**Comment by CumpsD** [comment]
I'm looking for these too, have they been removed?

I see there's a branch https://github.com/gravity00/SimpleSOAPClient/tree/SoapV1.2 for it, but I guess it didnt make it into 2.1
