### ISSUE TITLE
Create Request with raw Soap Xml string

### ISSUE THREAD

**Issue by thangtx** [gravity00/SimpleSOAPClient#23]
Hi
Please add method for Create Request with raw Soap Xml string.
Thanks

**Comment by gravity00** [comment]
You wan't to be able to send a string instead of creating a SOAP Envelope object, correct?

I'll analise that option, but for now, with RC03 you have at least two possibilities (being the first one my choice since it will validate your xml even before sending):

- Use the default `ISoapEnvelopeSerializationProvider` (or create one of your own) to deserialize your string into a SOAP Envelope and send it with the client. Example: 
```csharp
var requestEnvelope = SoapClientSettings.Default.SerializationProvider.ToSoapEnvelope(yourRawXml);
var responseEnvelope = await client.SendAsync("<url>", "<action>", requestEnvelope);
```
- Use an handler to replace the request content before sending it to the server. Example:
```csharp
using(var client = 
    SoapClient.Prepare().WithHandler(new DelegatingSoapHandler
    {
        OnHttpRequestAction = args => 
        {
            args.Request.Content = new StringContent(yourRawXml, Encoding.UTF8, "text/xml");
        }
    }))
{
    // send and empty envelope that will be replaced by your handler after being serialized
    var responseEnvelope = await client.SendAsync("<url>", "<action>", SoapEnvelope.Prepare());
}
```

> Note: the code may not completely compile, made it from memory.

**Comment by thangtx** [comment]
Ok, thank you :)
