### ISSUE TITLE
Unable to call services defined with soapAction=""

### ISSUE THREAD

**Issue by pthevenon** [gravity00/SimpleSOAPClient#28]
Hi,

A (poorly designed) service i need to integrate defines it's soapAction to "".

It seems valid wsdl, but SoapHandlerArguments constructor throws an argumenNullException if action is string.IsNullOrWhiteSpace().

Replacing check with if (action == null) seems to work fine ...

**Comment by gravity00** [comment]
Hi @pthevenon 

I'm in the middle of a major re-engineering for the final version 2.0.0 that should give developers a more easier control over the HttpSoapClient, more easily solving this cases due to poor services implementations.

In the mean time, my recommendation, is to pass some dummy string as the parameter and use the `OnHttpRequestAction` handler to override the HTTP Header "SOAPAction" before sending the request. Example:

```csharp
// Sample code for 2.0.0-rc03
public static async Task TestAsync(CancellationToken ct)
{
    using (var client =
        SoapClient.Prepare()
            .WithHandler(new DelegatingSoapHandler
            {
                OnHttpRequestAction = (c, args, cnt) =>
                {
		    // put here your replacement logic
                    args.Request.Headers.Add("SOAPAction", string.Empty);
                },
                OnSoapEnvelopeResponseAction = (c, args) =>
                {
                    // Bug: this action is required to prevent a NullReferenceException bug in RC03
                }
            }))
    {
        var requestEnvelope =
            SoapEnvelope.Prepare(); // create your soap envelope

        var responseEnvelope =
                await client.SendAsync(
                    "https://services.company.com/Service.svc",
                    "<dummy action>",
                    requestEnvelope, ct);
    }
}
```

_Note: this is an example code I made without compiling, but should give you an idea._

**Comment by pthevenon** [comment]
Thanks for your help, i got it to work.
